--- 
config.version: 15
install.component.samples: true
wgserver.authenticate: local

# The first in the list will be the primary (aka worker0). Then worker1, then worker2
worker.hosts: 10.0.0.1, 10.0.0.2, 10.0.0.3
worker.ports: 3730, 3730, 3730
# worker0
worker0.backgrounder.procs: 2
worker0.cacheserver.procs: 2
worker0.dataengine.procs: 1
worker0.dataserver.procs: 2
worker0.filestore.enabled: true
worker0.gateway.enabled: true
worker0.gateway.port: 8080
worker0.host: 10.0.0.1
worker0.vizportal.procs: 1
worker0.vizqlserver.procs: 2
worker0.zookeeper.procs: 1
#worker1
worker1.backgrounder.procs: 1
worker1.cacheserver.procs: 1
worker1.dataengine.procs: 1
worker1.dataserver.procs: 1
worker1.filestore.enabled: true
worker1.gateway.enabled: true
worker1.gateway.port: 8080
worker1.host: 10.0.0.2
worker1.vizportal.procs: 2
worker1.vizqlserver.procs: 1
worker1.zookeeper.procs: 1
#worker 2
worker2.backgrounder.procs: 1
worker2.cacheserver.procs: 1
worker2.dataengine.procs: 1
worker2.dataserver.procs: 1
worker2.filestore.enabled: true
worker2.gateway.enabled: false
worker2.gateway.port: 8080
worker2.host: 10.0.0.3
worker2.vizportal.procs: 1
worker2.vizqlserver.procs: 2
worker2.zookeeper.procs: 1


